// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ECH_yKd2N9gbFlIlJKUUcR1aL9LDr4Y',
    appId: '1:607168453417:web:a36efdd44e06eb0975b538',
    messagingSenderId: '607168453417',
    projectId: 'react-native-firebase-5a06a',
    authDomain: 'react-native-firebase-5a06a.firebaseapp.com',
    storageBucket: 'react-native-firebase-5a06a.appspot.com',
    measurementId: 'G-P3DXPT1HDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8MpdD-UEANZPEf51wOg1hDSaQmoyDRM',
    appId: '1:607168453417:android:6995d8f528eff7c875b538',
    messagingSenderId: '607168453417',
    projectId: 'react-native-firebase-5a06a',
    storageBucket: 'react-native-firebase-5a06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAFz0-Ac1baDMIrnoex_BDhiSYDzT8oes',
    appId: '1:607168453417:ios:6652cfe9e88e730875b538',
    messagingSenderId: '607168453417',
    projectId: 'react-native-firebase-5a06a',
    storageBucket: 'react-native-firebase-5a06a.appspot.com',
    iosClientId: '607168453417-gutb5dk8kj94vpmhm320c0e2fbfemjjg.apps.googleusercontent.com',
    iosBundleId: 'edu.shekhar.myPortfolio',
  );
}
